name: Create Release

on:
  push:
    branches: [release]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install
      - run: npm run build
      - run: npx vsce package --out flat-syntax.${{ github.sha }}.vsix
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "Release ${{ github.sha }}"
          files: |
            flat-syntax.${{ github.sha }}.vsix
